expences_proj/expences/account/urls.py
from django.urls import path
from .views import \
    AccountDetailView, \
    AccountListView, \
    AccountCreateView, \
    AccountDeleteView, \
    AccountUpdateView

app_name = 'account'


urlpatterns = [
    path('list/', AccountListView.as_view(), name='list'),
    path('<int:pk>/', AccountDetailView.as_view(), name='detail'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('<int:pk>/update', AccountUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', AccountDeleteView.as_view(), name='delete'),
]

expences_proj/expences/expences/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('transaction/', include('transaction.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

expences_proj/expences/main/urls.py
from django.urls import path
from .views import MainView

app_name = 'main'


urlpatterns = [
    path('', MainView.as_view(), name='index')
]

expences_proj/expences/transaction/urls.py
from django.urls import path
from .views import \
    TransactionDetailView, \
    TransactionListView, \
    TransactionCreateView, \
    TransactionDeleteView, \
    TransactionUpdateView

app_name = 'transaction'


urlpatterns = [
    path('list/', TransactionListView.as_view(), name='list'),
    path('<int:pk>/', TransactionDetailView.as_view(), name='detail'),
    path('create/', TransactionCreateView.as_view(), name='create'),
    path('<int:pk>/update', TransactionUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', TransactionDeleteView.as_view(), name='delete'),
]

expences_proj/expences/account/models.py
from django.db import models

# Create your models here.

expences_proj/expences/main/models.py
from django.contrib.auth.models import User
from django.db import models


class Currency(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name


class Account(models.Model):

    sum = models.IntegerField(default=0)
    currency = models.ForeignKey(Currency, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"Account of {self.user.first_name} {self.user.last_name}"


class Category(models.Model):

    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name


class Transaction(models.Model):

    sum = models.IntegerField(default=0)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, default=1)
    account = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Transaction {self.id} at {self.created_at}'

expences_proj/expences/transaction/models.py
from django.db import models

# Create your models here.

expences_proj/expences/account/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from main.models import Account
from main.views import menu


class AccountListView(ListView):

    model = Account
    template_name = 'account/account_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu(self.request)
        return context


class AccountDetailView(DetailView):

    model = Account
    template_name = 'account/account_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu(self.request)
        return context


class AccountCreateView(CreateView):
    model = Account
    fields = '__all__'
    template_name = 'account/account_form.html'
    success_url = reverse_lazy('account:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu(self.request)
        return context


class AccountUpdateView(UpdateView):
    model = Account
    fields = '__all__'
    template_name = 'account/account_form.html'
    success_url = reverse_lazy('account:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu(self.request)
        return context


class AccountDeleteView(DeleteView):
    model = Account
    template_name = 'account/account_confirm_delete.html'
    success_url = reverse_lazy('account:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu(self.request)
        return context

expences_proj/expences/main/views.py
# from django.contrib.auth.views import LoginView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.base import View


def menu(request):
    items = [
        {'name': 'Dashboard',
         'url': '/'},
        {'name': 'Accounts',
         'url': 'account/list'},
        {'name': 'Transactions',
         'url': 'transaction/list'},
    ]

    if request.user.is_authenticated:
        items.extend([
            {'name': 'Profile', 'url': 'profile/'},
            {'name': 'Logout', 'url': reverse_lazy('logout')}
        ])
    else:
        items.extend([
            {'name': 'Login', 'url': reverse_lazy('login')},
            {'name': 'Register', 'url': reverse_lazy('django_registration_register')}
        ])
    return items


class MainView(View):
    template_name = 'main/index.html'

    def get(self, request):
        context = {
            'menu': menu(request),
            'user': request.user if request.user.is_authenticated else None
        }
        return render(request, self.template_name, context)

# class MainLoginView(LoginView):
#     success_url = reverse_lazy('main:index')
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['menu'] = Menu().items
#         return context

expences_proj/expences/transaction/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from main.models import Transaction
from main.views import menu


class TransactionListView(ListView):

    model = Transaction
    template_name = 'transaction/transaction_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu(self.request)
        return context


class TransactionDetailView(DetailView):

    model = Transaction
    template_name = 'transaction/transaction_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu(self.request)
        return context


class TransactionCreateView(CreateView):
    model = Transaction
    fields = '__all__'
    template_name = 'transaction/transaction_form.html'
    success_url = reverse_lazy('transaction:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu(self.request)
        return context


class TransactionUpdateView(UpdateView):
    model = Transaction
    fields = '__all__'
    template_name = 'transaction/transaction_form.html'
    success_url = reverse_lazy('transaction:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu(self.request)
        return context


class TransactionDeleteView(DeleteView):
    model = Transaction
    template_name = 'transaction/transaction_confirm_delete.html'
    success_url = reverse_lazy('transaction:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu(self.request)
        return context

expences_proj/expences/main/templates/django_registration/registration_complete.html
{% extends "main/base.html" %}

{% block main %}

<p> Your account has been successfully created! </p>
    <button class="btn btn-primary"> <a href="{% url 'main:index' %}" style="color: lightgray"> To main page </a> </button>

{% endblock %}

expences_proj/expences/main/templates/django_registration/registration_form.html
{% extends "main/base.html" %}
{% load crispy_forms_filters %}

{% block main %}

{% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="">
{% csrf_token %}
{{ form | crispy }}
<input type="submit" class="btn btn-primary" value="Register" />
<input type="hidden" name="next" value="{{ next }}" />
<input type="submit" class="btn btn-outline-primary" onclick="window.location='{% url 'main:index' %}' ; return false;" value="Cancel">

</form>
{% endblock %}

expences_proj/expences/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href=" {% url 'main:index' %}">Dashboard</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        {% for item in menu %}
            {% if active %}
      <li class="nav-item active">
        <a class="nav-link" href="{{ item.url }}">{{ item.name }} <span class="sr-only">(current)</span></a>
      </li>
            {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{ item.url }}">{{ item.name }}</a>
      </li>
            {% endif %}
        {% endfor %}
    </ul>
  </div>
</nav>

<div class="container-fluid ml-4">

   {% block main %} {% endblock %}
</div>

</body>
</html>

expences_proj/expences/main/templates/main/detail.html
{% extends 'main/index.html' %}

{% block main %}

<h1>This is a detail view</h1>


<h2>{{ currency.name }} </h2>



{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<p></p>
<button> <a href="{% url 'main:list' %}"> Return to list </a></button>
{% endblock %}

expences_proj/expences/main/templates/main/index.html
{%  extends 'main/base.html' %}

{% block title %}
    Dashboard
{%  endblock %}
kjhjhjkh
{%  block main %}
    {% if user %}
    <h2>Welcome to Dashboard, {{ user }}!</h2>
    {% else %}
    <h2>Welcome to Dashboard!</h2>
        <p>Please proceed to <a href="{% url 'login' %}">login</a> to see the details</p>
    {% endif %}
{%  endblock %}

expences_proj/expences/main/templates/main/models_list.html
{% extends 'main/index.html' %}

{% block main %}

<h1>This is a list view</h1>


{% if currency_list %}
    <ul>
    {% for currency in currency_list %}
        <li><a href="{% url 'main:detail' currency.id %}">{{ currency.name }} </a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No currencies are available.</p>
{% endif %}
{% endblock %}

expences_proj/expences/transaction/templates/transaction/transaction_confirm_delete.html
{% extends 'main/base.html' %}
{% block title %} Delete Transaction {% endblock %}
{% block main %}

<h1>Delete Transaction</h1>

<p>Are you sure you want to delete this transaction {{ transaction.id }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Yes, delete.">
  <input type="submit" class="btn btn-outline-danger"
         onclick="window.location='{% url 'transaction:list' %}' ; return false;" value="Cancel">
</form>




{% endblock %}

expences_proj/expences/transaction/templates/transaction/transaction_detail.html
{% extends 'main/base.html' %}
{% block title %}
    Account
{% endblock %}
{% block main %}


<h2>{{ transaction }} ({{ transaction.id  }})</h2>
    <p>Sum: {{ transaction.sum }} {{  transaction.currency.name }}</p>
    <p>Category: {{ transaction.category.name }}</p>




{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<p></p>
<button class="btn btn-primary"> <a href="{% url 'transaction:list' %}" class="text-white"> Return to list </a></button>
{% endblock %}

expences_proj/expences/transaction/templates/transaction/transaction_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %} Add transaction {% endblock %}

{% block main %}
    <div class="row">

    <div class="col-4">
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="Submit">
    <input type="submit" class="btn btn-outline-primary" value="Cancel" onclick="window.location.href='{% url 'transaction:list' %}';return false;">
  </form>
        </div>
    </div>
{% endblock %}

expences_proj/expences/transaction/templates/transaction/transaction_list.html
{% extends 'main/base.html' %}
{% block title %} All transactions {% endblock %}

{% block main %}
    <div class="row">

    </div>
    <div class="row">
    <a href="{% url 'transaction:create' %}">Add Transaction</a>
    </div>


{% if transaction_list %}
    <div class="row">
    <ul>
    {% for transaction in transaction_list %}
        <li><a href="{% url 'transaction:detail' transaction.id %}">{{ transaction }} </a>
            {% if user.id == transaction.account.user.id %}
        (<a href="{% url 'transaction:update' transaction.id %}">Update</a> |
          <a href="{% url 'transaction:delete' transaction.id %}">Delete</a>) <br/>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
    </div>
{% else %}
    <div class="row">
    <p>No transactions are available.</p>
    </div>

{% endif %}
{% endblock %}