Flask/__init__.py
from .views.portfolio import portfolio_app

Flask/app.py
from flask import Flask

from .views.portfolio import portfolio_app

app = Flask(__name__)
app.register_blueprint(portfolio_app, url_prefix="/portfolio")


@app.route("/")
def index():
    return "<h1><em>Base page</em></h1>"

Flask/main.py
from app import app

app.config.update(
    DEBUG=True,
)


if __name__ == "__main__":
    app.run(debug=True)

Flask/views/portfolio.py
from flask import Blueprint, render_template

portfolio_app = Blueprint("portfolio_app", __name__)


def get_menu():
    menu = [
        {'url': f'/portfolio/certificates', 'name': 'Certificates'},
        {'url': f'/portfolio/projects', 'name': 'Projects'},
    ]
    return menu


@portfolio_app.route("/")
def portfolio():
    context = {
        'main_message': 'My Portfolio',
        'main_text': 'Welcome to my portfolio website! Here you can take a look at projects I '
                     'took part in and check out my certificates from online courses I completed'
    }
    return render_template("portfolio/main.html", menu=get_menu(), context=context)


@portfolio_app.route("/certificates")
def certificates():
    context = {
        'main_message': 'My Certificates',
        'certif_list': [
            {'url': 'https://www.coursera.org/account/accomplishments/certificate/FBRH36YMKU4N',
             'name': 'Web Technologies and Django'},
            {'url': 'https://geekbrains.ru/certificates/453624', 'name': 'HTML5 & CSS3'},
            {'url': 'https://geekbrains.ru/certificates/554013', 'name': 'Databases for Web'},
            {'url': 'https://geekbrains.ru/certificates/585182', 'name': 'Yii2 Framework'},
            {'url': 'https://geekbrains.ru/certificates/523916', 'name': 'A Quickstart to Git'},
        ]
    }
    return render_template("portfolio/certif.html", menu=get_menu(), context=context)


@portfolio_app.route("/projects")
def projects():
    context = {
        'main_message': 'My Projects',
        'proj_list': [
            {'url': 'https://github.com/fortys1xandtwo/SimpleVotings08',
             'name': 'Simple Votings'},
            {'url': 'https://prom.informatics.ru/2020/online/s101/', 'name': 'Minute of Fame'},
        ]
    }
    return render_template("portfolio/proj.html", menu=get_menu(), context=context)

Flask/templates/portfolio/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>
        {% block title %}
        {{ pagetitle }}
        {% endblock %}
    </title>

    <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block custom_css %}
    <link href="{{ url_for('static', filename='portfolio/custom.css') }}" rel="stylesheet" >
    {% endblock %}
</head>
<body>
<header>
    {% block menu %}
    {% include 'portfolio/menu.html' %}
    {% endblock %}
</header>
<!-- /header -->
<div class="container mt-5">
    <main>

        {% block message %}
        <div class="card bg-light my-3 py-2 text-center">
            <div class="card-body">
                <p class="text-dark m-0"> {{ context.main_message }}</p>
            </div>
        </div>
        {% endblock %}

        <div class="card bg-light my-3 py-2 text-center">
            <div class="card-body">
                        {% block main %}
        {% endblock %}
            </div>
        </div>

    </main>
</div>
<footer class="footer pt-3 bg-dark">
    {% block footer %}
    <div class="container">
        <p class="text-muted"><a href="#" title="" class="text-light">&copy; 2020</a>.
        </p>
    </div>
    {% endblock %}
</footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
{% block custom_js %} {% endblock %}
</body>
</html>

Flask/templates/portfolio/certif.html
{% extends 'portfolio/base.html' %}

{% block main %}



<ul>
    {% for item in context.certif_list %}
    <li> <a href="{{item.url}}" target="_blank"> {{item.name}} </a></li>
    {% endfor %}
</ul>

{% endblock %}

Flask/templates/portfolio/main.html
{% extends 'portfolio/base.html' %}

{% block main %}
<p class="text-dark m-0"> {{ context.main_text }}</p>

{% endblock %}

Flask/templates/portfolio/menu.html
{% if menu %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('portfolio_app.portfolio') }}">MP</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% for item in menu %}
<!--                {% if item.dropdown %}-->
<!--                <div class="dropdown">-->
<!--                    <li class="nav-item">-->
<!--                        <a class="nav-link dropdown-toggle"-->
<!--                           id="dropdownMenuButton" data-toggle="dropdown"-->
<!--                           aria-haspopup="true" aria-expanded="false" href="{{ item.url }}">{{ item.name }}</a>-->
<!--                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">-->
<!--                            {% for i in item.dropdown %}-->
<!--                            <a class="dropdown-item" href="{{ i.url }}">{{ i.name }} </a>-->
<!--                            {% endfor %}-->
<!--                        </div>-->
<!--                    </li>-->
<!--                </div>-->
<!--                {% else %}-->
                <li class="nav-item">
                    <a class="nav-link" href="{{ item.url }}">{{ item.name }}</a>
                </li>
<!--                {% endif %}-->
                {% endfor %}

<!--                {% for item in menu.0 %}-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{{item.url}}">{{ item.name }}-->
<!--                        <span class="sr-only">(current)</span>-->
<!--                    </a>-->
<!--                </li>-->
<!--                {% endfor %}-->
            </ul>
        </div>
    </div>
</nav>

{% endif %}

Flask/templates/portfolio/proj.html
{% extends 'portfolio/base.html' %}

{% block main %}
<ul>
    {% for item in context.proj_list %}
    <li> <a href="{{item.url}}" target="_blank"> {{item.name}} </a></li>
    {% endfor %}
</ul>
{% endblock %}